site_name: "Révision L3-S6"
site_url: https://t1m045.github.io/revision-l3/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

copyright: "UPEC - REVISION"

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter

extra:
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
